#!/usr/bin/env python3
"""Pin the CONTENTS of the input/output maps as bytes, so a move cannot lose a binding.

Why this exists and the probes do not
-------------------------------------
`scripts/probe_fixes.py` has five probes that reach into `batch_configs.CONFIGS`, and they are good
probes -- but every one of them synthesizes the *declared* side of its comparison FROM that same map
(`probe_fixes.py:503` and `:532` iterate `bc.CONFIGS` to build the fixture WDL). So a binding deleted
in the middle of a refactor vanishes from both sides of the comparison and every probe stays green.
They grade the comparison machinery; they have never graded the table. This file is the one check
whose only input is the shipped table and whose only oracle is a checked-in byte-for-byte capture.

Two artifacts, both regenerated by `--write` from the fixture profile
`scripts/selftest.d/fixtures/genotyping.profile.env` (placeholders only, no user config, no network):

  scripts/selftest.d/golden/configs-show.txt   the stdout of `batch_configs.py show`
  scripts/selftest.d/golden/configs-body.json  `body()` for every config, in CONFIGS order

`show` is pinned because it is what the docs promise is "what gets POSTed". `body()` is pinned
separately because `show` does not print every field it builds (`useCallCache`,
`deleteIntermediateOutputFiles`, `methodConfigVersion`, `prerequisites`), and those are exactly the
fields a refactor could quietly move.

CAPTURE COMMAND, byte for byte, on a machine with no profile:

    GSVTK_CONFIG=scripts/selftest.d/fixtures/genotyping.profile.env \
    GSVTK_WORK=$(mktemp -d) .venv/bin/python scripts/golden_configs.py --write

THE POSITIVE CONTROL, which is the whole argument (`--control`, and CONTRIBUTING's "every checker
assertion needs a positive control"): the planted defect is a binding dropped from an in-memory COPY
of the table, twice -- once an input on step 06, once an output on step 10. Both must make the
comparison FAIL. Before planting anything the control asserts the untouched capture PASSES, because
a check that already fails cannot be shown to notice anything, and a "control" that reports fire on
a broken baseline proves nothing.

Offline by construction: `show` and `body()` need no credentials, no ref and no checkout, and the
scratch path is never created (`kit/config.work_path`, not `work_dir`).

python 3.9+.
"""
from __future__ import annotations

import argparse
import copy
import io
import json
import os
import sys
import tempfile
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PROFILE = ROOT / "scripts/selftest.d/fixtures/genotyping.profile.env"
GOLDEN_DIR = ROOT / "scripts/selftest.d/golden"
SHOW_GOLDEN = GOLDEN_DIR / "configs-show.txt"
BODY_GOLDEN = GOLDEN_DIR / "configs-body.json"

# The planted defects for `--control`: (config, map, key). Step 06 rather than step 10 on purpose --
# the rerun lane's golden covers step 10's inputs, and a control that only ever fires on the config
# another lane pins would leave four of the five maps unguarded.
PLANTED = [
    ("06-GenerateBatchMetrics", "inputs", "GenerateBatchMetrics.median_file"),
    ("10-GenotypeBatch", "outputs", "GenotypeBatch.regeno_coverage_medians"),
]


def _setup_env() -> str:
    """Point the config layer at the fixture profile BEFORE anything imports kit.config.

    `kit/config.py` resolves the profile chain at import, so an interpreter that has already read a
    real `testkit.env` cannot be re-pointed afterwards. GSVTK_WORK is required by name at import
    (`batch_configs.DUMP` is a `work_path`, which calls `require("WORK")`) and is never created by a
    read-only command -- a throwaway value here is what lets this run with no user profile at all.
    """
    if not os.environ.get("GSVTK_CONFIG"):
        os.environ["GSVTK_CONFIG"] = str(FIXTURE_PROFILE)
    if not os.environ.get("GSVTK_WORK"):
        os.environ["GSVTK_WORK"] = tempfile.mkdtemp(prefix="gsvtk-golden-")
    return os.environ["GSVTK_CONFIG"]


def _load_configs():
    sys.path.insert(0, str(ROOT / "kit"))
    sys.path.insert(0, str(ROOT / "terra"))
    import batch_configs                          # noqa: E402  (kit/terra are siblings by path)
    return batch_configs


def capture() -> dict:
    """(show stdout, bodies as JSON text) for the table as it stands in this checkout."""
    bc = _load_configs()
    out = io.StringIO()
    with redirect_stdout(out):
        bc.show()
    bodies = [bc.body(n) for n in bc.CONFIGS]
    return {"show": out.getvalue(),
            "body": json.dumps(bodies, indent=1) + "\n",
            "counts": {"configs": len(bc.CONFIGS),
                       "inputs": sum(len(s["inputs"]) for s in bc.CONFIGS.values()),
                       "outputs": sum(len(s.get("outputs") or {}) for s in bc.CONFIGS.values())}}


def _diff(label: str, want: str, got: str) -> list:
    """Byte comparison with a findable first difference, not just "different"."""
    if want == got:
        return []
    wl, gl = want.splitlines(), got.splitlines()
    lines = [f"{label}: {len(wl)} golden line(s) vs {len(gl)} now"]
    for i, (a, b) in enumerate(zip(wl, gl)):
        if a != b:
            lines.append(f"  line {i + 1}:")
            lines.append(f"    golden: {a}")
            lines.append(f"    now   : {b}")
            break
    if len(wl) != len(gl) and all(a == b for a, b in zip(wl, gl)):
        longer, tag = (wl, "golden") if len(wl) > len(gl) else (gl, "now")
        lines.append(f"  {tag} carries the extra line(s):")
        for extra in longer[min(len(wl), len(gl)):][:6]:
            lines.append(f"    {extra}")
    return lines


def _compare(cap: dict) -> list:
    """Every finding from comparing a capture to the goldens on disk. Empty means byte-identical."""
    problems = []
    for path, key in ((SHOW_GOLDEN, "show"), (BODY_GOLDEN, "body")):
        if not path.is_file():
            problems.append(f"{path.relative_to(ROOT)}: no golden on disk "
                            f"(run `scripts/golden_configs.py --write`)")
            continue
        want = path.read_text()
        problems += _diff(f"{path.relative_to(ROOT)}", want, cap[key])
    return problems


def _tally(cap: dict) -> str:
    c = cap["counts"]
    return (f"{c['configs']} config(s), {c['inputs']} input binding(s), "
            f"{c['outputs']} output binding(s)")


def cmd_check() -> int:
    cap = capture()
    if not cap["counts"]["configs"]:
        # The empty-input rule: a comparison over zero configs is not a pass, whatever it prints.
        print("golden: FAIL -- the table holds 0 configs, so NOTHING was compared")
        return 1
    problems = _compare(cap)
    if problems:
        print("golden: FAIL -- the maps moved and this is the check that notices")
        for p in problems:
            print("  " + p)
        print(f"  compared: {_tally(cap)} against {SHOW_GOLDEN.relative_to(ROOT)} + "
              f"{BODY_GOLDEN.relative_to(ROOT)}")
        return 1
    print(f"golden: ok -- {_tally(cap)} byte-identical to the goldens in "
          f"{GOLDEN_DIR.relative_to(ROOT)}/")
    return 0


def cmd_write() -> int:
    cap = capture()
    if not cap["counts"]["configs"]:
        print("golden: refused -- 0 configs, so the golden would pin nothing", file=sys.stderr)
        return 1
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    SHOW_GOLDEN.write_text(cap["show"])
    BODY_GOLDEN.write_text(cap["body"])
    print(f"golden: wrote {SHOW_GOLDEN.relative_to(ROOT)} ({len(cap['show'].splitlines())} lines) "
          f"and {BODY_GOLDEN.relative_to(ROOT)} ({len(cap['body'].splitlines())} lines)")
    print(f"        from {_setup_env()} -- {_tally(cap)}")
    return 0


def cmd_control() -> int:
    """The check must FAIL on a planted defect, and PASS without one. Both halves or nothing."""
    bc = _load_configs()
    base = capture()
    if _compare(base):
        # Without this, "the control fired" is meaningless: a broken baseline reports a difference
        # against any mutation, and the checker that checks nothing passes again.
        print("control: FAIL -- the baseline does not match the goldens, so a planted drop would "
              "report a difference it did not cause")
        for p in _compare(base):
            print("  " + p)
        return 1
    print(f"  ok    baseline: {_tally(base)} matches the goldens (the control needs this to mean "
          f"anything)")
    bad = 0
    original = bc.CONFIGS
    for name, which, key in PLANTED:
        bc.CONFIGS = copy.deepcopy(original)
        try:
            del bc.CONFIGS[name][which][key]
            mutated = capture()
        finally:
            bc.CONFIGS = original
        problems = _compare(mutated)
        if problems:
            print(f"  ok    planted drop of {key} from {name}.{which} -> the golden check FAILS")
            for p in problems[:1]:
                print(f"        {p}")
        else:
            bad += 1
            print(f"  FAIL  planted drop of {key} from {name}.{which} -> the golden check PASSED")
            print("        the golden is vacuous: a binding can be deleted in a refactor and nothing")
            print("        in this repo will notice. That is the exact hole docs/module-profiles.md §9")
            print("        step 1 says the probes leave open.")
    if bad:
        print(f"control: {bad} planted defect(s) went unnoticed")
        return 1
    print(f"control: ok -- {len(PLANTED)} planted binding drop(s) each made the check fail, and the "
          f"unmutated\ncapture passed first, so neither result came from a broken baseline")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                               epilog="The default action is `check`: compare the live maps to the "
                                      "goldens, byte for byte.")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true",
                   help="regenerate both goldens from the fixture profile (review the diff)")
    g.add_argument("--control", action="store_true",
                   help="plant a dropped binding in a copy of the table and require the check to FAIL")
    a = p.parse_args()
    profile = _setup_env()
    print(f"golden: fixture profile {profile}  (no user profile, no network)")
    if a.write:
        return cmd_write()
    if a.control:
        return cmd_control()
    return cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
